services:
  - type: web
    name: polla-oi8i
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_URL
        value: https://polla-oi8i.onrender.com
      - key: AUTH_URL
        value: https://polla-oi8i.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: AUTH_SECRET
        generateValue: true
      - key: AUTH_TRUST_HOST
        value: "true"
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: https://polla-oi8i.onrender.com
