services:
  - type: web
    name: polla-deportiva
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_URL
        value: https://polla-oi8i.onrender.com
      - key: AUTH_URL
        value: https://polla-oi8i.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PRISMA_CLIENT_ENGINE_TYPE
        value: library
